### PR TITLE
fix nil dereference when service is not maintained in webhook conversion

### LINKED ISSUE #60: nil pointer dereference in conversion webhook
Having a conversion webhook in a CRD which points to an URL and not to a service will cause a nil pointer deference. The affected code line: https://github.com/arttor/helmify/blob/7205b074d20cf10f0065335a093f58a7b3b10f04/pkg/processor/crd/crd.go#L120

According to k8s docs it can be either a service or an URL: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#url

### PR DESCRIPTION
**Pull request by stotz89**
fixes #60

### CODE REVIEW

File: pkg/processor/crd/crd.go [hunk 1]
```diff
@@ -116,7 +116,7 @@ func (c crd) Process(appMeta helmify.AppMetadata, obj *unstructured.Unstructured
 		conv := spec.Conversion
 		if conv.Strategy == v1.WebhookConverter {
 			wh := conv.Webhook
-			if wh != nil {
+			if wh.ClientConfig.Service != nil {
```
Comment (arttor) [inline pkg/processor/crd/crd.go:119]:
```suggestion
			if wh != nil && wh.ClientConfig != nil &&  wh.ClientConfig.Service != nil {
```

**Review by arttor — APPROVED** [review]
